# Generated by Django 5.2.14 on 2026-06-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bug", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugreport",
            name="reporter_phone_number",
        ),
        migrations.AddField(
            model_name="bugreport",
            name="ai_suggestion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
