# Generated by Django 5.2.3 on 2026-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bug", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bugreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterModelTable(
            name="bugreport",
            table="bug_report",
        ),
    ]
