# Generated by Django 5.2.14 on 2026-06-12 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bug", "0002_remove_bugreport_reporter_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugreport",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="bug.bugreport",
            ),
        ),
        migrations.AddField(
            model_name="bugreport",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
    ]
